### ISSUE TITLE
Hash changes when scrolling a page

### ISSUE THREAD

**Issue by OrelSBinoklem** [rmjordas/awesome-vue#5]
Because of this, I had to add the site to my favorites several times, but the browser showed me that the site was not in my favorites

**Comment by OrelSBinoklem** [comment]
Page example [https://awesome-vue.js.org/components-and-libraries/ui-components.html#notification](url)

**Comment by rmjordas** [comment]
@OrelSBinoklem I've tweak the config to disable the URL hash change on scroll behavior. Let me know if this works for you. You might need to force refresh the page to see it (usually it's Ctrl+F5 if you're using a desktop). :+1:

**Comment by OrelSBinoklem** [comment]
Its work, thank You)
