### ISSUE TITLE
broken link: resources/community.html

### ISSUE THREAD

**Issue by BaseMax** [rmjordas/awesome-vue#52]
https://t.me/vue_commerce wrong link

https://github.com/rmjordas/awesome-vue/edit/master/content/resources/community.md

https://awesome-vue.js.org/resources/community.html

**Comment by rmjordas** [comment]
Hello @BaseMax. 

Kindly refer to the contributing guide available at:

> https://github.com/rmjordas/awesome-vue/blob/master/.github/CONTRIBUTING.md

In the document above, you would see a link to the official "awesome list" repository of the Vue.js project. Please read their contribution guide and open a pull request on that repository with information about the changes you want to propose. If they accept your proposal, I will make sure to also included the merged changes in my repository and at https://awesome-vue.js.org.

Thanks.

**Comment by BaseMax** [comment]
Hi, I mean that telegram link is not correct on the page.

**Comment by rmjordas** [comment]
I consulted the official awesome-vue repository and saw that the entry was no longer there. I must've missed it when they removed it. 

Thank you for opening this issue. 👍
