### ISSUE TITLE
Very few libraries added for Vue3

### ISSUE THREAD

**Issue by runxc1** [rmjordas/awesome-vue#58]
I've been working on a Vue3 project for a number of months now and am finding it difficult to locate good libraries and components that work with Vue3.   Using Vue2 I used to use this curated list but have found it either hasn't been updated to add Vue3 options or really is mostly for Vue2.   It seems with Vue3 being live now there would be more options for Vue3 here.

**Comment by rmjordas** [comment]
Hello @runxc1 

I've added a link on the homepage that goes to the next version of the website. You can also view it by going to https://next.awesome-vue.js.org

The content on the new website is updated to include some projects that are compatible with Vue 3.

Note: Search box is not configured properly.

Hope this helps.

**Comment by last-partizan** [comment]
Fucking @github-actions. This should be open.
