### ISSUE TITLE
Broken link for bootstrap4editor

### ISSUE THREAD

**Issue by Lyokolux** [rmjordas/awesome-vue#69]
On the page https://awesome-vue.js.org/projects-using-vue-js/interactive-experiences.html

the link Bootstrap4Editor (https://www.itwonders-web.com/bootstrap4-editor/) returns a 404 not found

**Comment by rmjordas** [comment]
Hello @Lyokolux.

Kindly refer to the contributing guide available at:

https://github.com/rmjordas/awesome-vue/blob/master/.github/CONTRIBUTING.md

In the document above, you would see a link to the official "awesome list" repository of the Vue.js project. Please read their contribution guide and open a pull request on that repository with information about the changes you want to propose. If they accept your proposal, I will make sure to also included the merged changes in my repository and at https://awesome-vue.js.org.

Thanks.
